/*英文包 en*/
export default {
  //景区服务商列表表头
  sceneryProviderInfo:{
    'providerId':'serviceProviderID',
    'providerName':'serviceProviderName',
    'loginName':'loginName',
    'facilityAmount':'facilityAmount',
    'onlineAmount':'onlineAmount',
    'offlineAmount':'offlineAmount',
    'dutyName':'dutyName',
    'dutyPhone':'dutyPhone',
    'address':'address',
  },
  sceneryGroupPersonInfo: {
    'name':'name',
    'isOnline':'isOnline'
  },
  sceneryScopeListInfo: {
    'name':'sceneryName',
    'isEnabled':'isEnabled'
  },
  roadLineInfo: {
    'name':'roadLineName',
    'type':'roadLineType',
    'destination':'destination'
  },
  roadLineScenerySpotInfo: {
    'name':'scenerySpotName',
    'grade':'scenerySpotGrade',
    'address':'sceneryAddress',
    'tel':'phone',
    'state':'state'
  },
  railInfo: {
    'name':'railName',
    'sceneryName':'sceneryName',
    'type':'alertType',
    'isEnabled':'isEnabled',
    'hintMode':'hintMode',
    'inHintWord':'inHintWord',
    'outHintWord':'outHintWord'
  },
  singleText:{
    'alert':'ALERT',
    'search':'Search',
    'searchInfo':'enter code for search',
    'language':'中文',
    'loginOut':'LoginOut',
    'handle':'handle',
  },
  login:{
    'title' : 'Software system',
    'username' : 'Please enter the user name',
    'password' : 'Please enter your password',
    'login' : 'Login',
    'language' : 'Please select language'
  },
  queryName:{
    searchIfInfo:'search condition',
    loginName:'login name',
    sceneryName:'scenery name',
    organization:'organization name',
    affiliatedScenery:'affiliated scenery',
    affiliatedSceneryRRR:'affiliated scenery',
    affiliatedAreaRRR:'affiliated area',
    affiliatedSpot:'affiliated spot',
    spotName:'spot name',
    facilitySort:'facility sort',
    businessType:'business type',
    roadLineType:'roadLine type',
    sexType:'sex type',
    roadLineName:'roadLine name',
    facilityName:'facility name',
    serviceProviderSerialNum:'serviceProvider serialNum',
    roleName:'role name',
    jurisdictionTag:'jurisdiction tag',
    serviceProviderName:'serviceProvider name',
    operatorName:'operator name',
    serviceProviderLinkMan:'serviceProvider linkMan',
    rentTime:'rent time',
    dateShow:'time',
    allocationState:'allocation State',
    userTel:'phone number',
    guideTel:'guide phoneNum',
    userSerialNum:'user serialNum',
    guideSerialNum:'guide SerialNum',
    registerDate:'register date',
    monthDate:'search month',
    touristGroup2:'tourist group',
    rfidSerialNum:'rfid serialNum',
    rfidType:'rfid type',
    sceneryGrade:'scenery grade',
    affilitedArea:'affilited area',
    affiliatedTourCompany:'affiliated tourCompany',
    tourCompanyName:'tourCompany name',
    personName:'linkMan name',
    groupNum:'group number',
    createGroupTime:'createGroup time',
    createGroupTime2:'search time',
    coverageName:'coverage name',
    travelInfoName:'travel name',
    railName:'rail name',
    versionNum:'version num',
    imeiNum:'imei num',
    codeMachine:'machine code',
    mediaFileSerialNum:'mediaFile serialNum',
    mediaFileName:'mediaFile name',
    mediaType:'media type',
    canChooseScenery:'choose scenery',
    a2ChooseServiceProvider:'A2 serviceProvider name',
    messageHeader:'message header',
    publishType:'publish type',
    sosTime:'sos time',
    visitDate:'visit date',
    publishDate:'publish time',
    paramKey:'param key',
    paramValue:'param value',
    editorScope:'editor scope',
    publishState:'publish state',
    publishStateK:'resource bundle state',
    reset:'is or not reset',
    touristState:'tourist state',
    sceneryState:'state',
    isOnLineState:'onLine state',
    groupPersonType:'member type',
    alertType:'alert type',
    myUpdateState:'update state',
    routeNameShow:'route name',
    sosDateShow:'sos date',
  },
  placeholderInfo: {
    searchIfInfo:'enter condition',
    loginName:'enter login name',
    sceneryName:'enter scenery name',
    organization:'enter organization name',
    affiliatedScenery:'choose affiliated scenery',
    affiliatedSceneryRRR:'enter affiliated scenery',
    affiliatedAreaRRR:'enter affiliated area',
    affiliatedSpot:'enter affiliated spot',
    spotName:'enter spot name',
    facilitySort:'enter facility sort',
    businessType:'choose business type',
    roadLineType:'choose roadLine type',
    sexType:'choose sex type',
    roadLineName:'enter roadLine name',
    facilityName:'enter facility name',
    serviceProviderSerialNum:'enter serviceProvider serialNum',
    roleName:'enter roleName',
    jurisdictionTag:'enter jurisdictionTag',
    serviceProviderName:'enter serviceProvider name',
    operatorName:'enter operator name',
    serviceProviderLinkMan:'enter serviceProvider linkMan',
    rentTime:'choose rentTime',
    allocationState:'choose allocationState',
    userTel:'enter phoneNum',
    guideTel:'enter guideTel',
    userSerialNum:'enter userSerialNum',
    guideSerialNum:'enter guideSerialNum',
    registerDate:'',
    touristGroup2:'choose touristGroup',
    rfidSerialNum:'enter rfid serialNum',
    rfidType:'choose rfidType',
    sceneryGrade:'choose sceneryGrade',
    affilitedArea:'choose affilitedArea',
    affiliatedTourCompany:'enter affiliated tourCompany',
    tourCompanyName:'enter tourCompany name',
    personName:'enter tourCompany linkMan',
    groupNum:'enter groupNum',
    coverageName:'enter coverageName',
    travelInfoName:'enter travel name',
    railName:'enter railName',
    versionNum:'enter versionNum',
    imeiNum:'enter imei number',
    codeMachine:'enter machineCode',
    mediaFileSerialNum:'enter mediaFile serialNum',
    mediaFileName:'enter mediaFile name',
    mediaType:'choose mediaType',
    canChooseScenery:'choose scenery',
    a2ChooseServiceProvider:'choose serviceProvider name',
    messageHeader:'enter messageHeader',
    publishType:'choose publishType',
    sosTime:'choose sos time',
    visitDate:'choose visitDate',
    publishDate:'choose publishTime',
    paramKey:'enter paramKey',
    paramValue:'enter paramValue',
    editorScope:'choose editorScope',
    publishState:'choose publishState',
    publishStateK:'choose resourceBundle state',
    reset:'choose is or not reset',
    touristState:'choose touristState',
    sceneryState:'choose state',
    isOnLineState:'choose onLine state',
    groupPersonType:'choose member type',
    alertType:'choose alertType',
    myUpdateState:'choose updataState',
    routeNameShow:'enter routeName',
  },
  btnInfo:{
    add:'add',
    add1:'add',
    areaManage:'area manage',
    return:'return',
    moreDel:'more delete',
    editor:'edit',
    addGroup:'addGroup',
    editGroup:'editGroup',
    closeGroup:'closeGroup',
    enabled:'enabled',
    disabled:'disabled',
    abandon:'abandon',
    coverageManage:'coverageManage',
    railTipSet:'railTipSet',
    sceneryScope:'sceneryScope',
    oneKeyTurnOff:'oneKeyTurnOff',
    languageConfig:'languageConfig',
    resourceBundle:'resourceBundle',
    mapPreview:'mapPreview',
    sceneryInfo:'sceneryInfo',
    spotInfo:'spotInfo',
    delete:'delete',
    sureMessage:'sureMessage',
    sosDispose:'sosDispose',
    adjustTravelAgency:'adjustTravelAgency',
    authentication:'authentication',
    cancelAuthentication:'cancelAuthentication',
    relevanceGuide:'relevanceGuide',
    cancelRelevance:'cancelRelevance',
    publish:'publish',
    cancelPublish:'cancelPublish',
    updateInfo:'updateInfo',
    addFacility:'addFacility',
    synRedis:'synRedis',
    impower:'impower',
    impowerScenery:'impowerScenery',
    impowerRole:'impowerRole',
    impowerFunction:'impowerFunction',
    heavyLoadImp:'heavyLoadImp',
    resetPsd:'resetPsd',
    allotFacility:'allotFacility',
    importRfid:'importRfid',
    importFacility:'importFacility',
    exportFacility:'exportFacility',
    downloadExcelTemplate:'downloadExcelTemplate',
    clearTravel:'clearTravel',
    clearAlert:'clearAlert',
    userLog:'userLog',
    operatorLog:'operatorLog',
    businessLog:'businessLog',
    query:'Query',
  },
  textInfo1:{
    facilityCount:'facilityCount',
    onlineCount:'onlineCount',
    offlineCount:'offlineCount',
    site:'SITE',
    enabledCount:'enabledCount',
    disabledCount:'disabledCount',
  },
  homeTitle:{
    online:'onLine',
    offline:'offLine',
    alert:'alert',
    facilityCount:'facilityCount',
    onlineCount:'onlineCount',
    onlineRate:'onlineRate',
    query:'Query',
    alertS:'Alert',
  }

}
